FROM python:3.11-bullseye

## Top level args / env vars
ARG USER=user
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DEBIAN_FRONTEND=noninteractive

## Apt based dependencies
RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get -y install \
    curl \
    build-essential \
    git \
    jq \
    graphviz \
    vim \
    wget \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

## Create unpriv user
RUN groupadd --gid $USER_GID $USER \
    && useradd --uid $USER_UID --gid $USER_GID -m $USER \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USER ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USER \
    && chmod 0440 /etc/sudoers.d/$USER \
    && rm -rf /var/lib/apt/lists/*

## Install oh my zsh
# Uses "Spaceship" theme with some customization. Uses some bundled plugins and installs some more from github
USER ${USER}
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)" -- \
    -t https://github.com/denysdovhan/spaceship-prompt \
    -a 'SPACESHIP_PROMPT_ADD_NEWLINE="false"' \
    -a 'SPACESHIP_PROMPT_SEPARATE_LINE="false"' \
    -p git \
    -p ssh-agent \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions
USER root


ENV PROJ_ROOT=/opt/prompting_techniques
RUN mkdir -p ${PROJ_ROOT}/prompting_techniques && chown $USER -R /opt/
USER ${USER}
WORKDIR ${PROJ_ROOT}
RUN python3 -m pip install --user poetry
COPY --chown=${USER} pyproject.toml README.md ${PROJ_ROOT}
RUN python3 -m poetry config virtualenvs.in-project true
RUN python3 -m poetry install --no-root --with dev
COPY ./prompting_techniques/* ${PROJ_ROOT}/prompting_techniques
RUN python3 -m poetry install
